keyMirror = (m, v) -> m[v] = v; m

module.exports = [
	'APP_MAIN',
	'GET_MUSIC',
	'APP_RESIZE',

	'PAGE_CHANGING',
	'LOADED_PLAYLIST',
	'LOADED_BROWSE',
	'LOADED_REMOTE',
	'LOADED_SONG',

	'AUTHENTICATED',
	'MESSAGE',
	'MESSAGE_REPEAT',

	'SONG_CHANGED',
	'LOADED_MUSIC',

	'PROGRESS_CURRENT',
	'PROGRESS_LOADED',
	'PROGRESS_DURATION',

	'SONG_CLICKED',
	'SONG_ACTIVATED',
	'CONTROLS_VOLUME',
	'CONTROLS_FORWARD',
	'CONTROLS_BACKWARD',
	'CONTROLS_PLAY',
	'CONTROLS_SORTMETHOD',
	'CONTROLS_SEEKTO',
	'DRAGGING_STOPPED',

	'PLAYER_PAUSED',
	'PLAYER_ENDED',
	'PLAYER_PLAYING',
	'PLAYER_UNSTARTED',
	'PLAYER_CUED',
	'PLAYER_BUFFERING',
	'ENDED',
	'PLAYING',
	'PAUSED',

	'SOUNDCLOUD_TRACK_RECEIVED',
	'VIMEO_READY',
	'VIMEO_PLAYPROGRESS',
	'VIMEO_PAUSE',
	'VIMEO_FINISH',
	'VIMEO_PLAY',
	'VIMEO_LOADPROGRESS',
	'VIMEO_GET_VIDEOHEIGHT',
	'VIMEO_GET_VIDEOWIDTH',
	'YOUTUBE_IFRAMEREADY',

	'REMOTE_SUBREDDITS'
].reduce keyMirror, {}
